name: http_request_utils
description: Http requests utils
version: 0.2.0
homepage: https://github.com/Djcharles26/
repository: https://github.com/Djcharles26/http_utils.git

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


# The following section is specific to Flutter.
flutter: